

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."modpacks" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "backet_path" character varying NOT NULL
);


ALTER TABLE "public"."modpacks" OWNER TO "postgres";


ALTER TABLE "public"."modpacks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."modpacks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."versions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "modpack_name" character varying NOT NULL,
    "modpack_version" "text",
    "minecraft_version" "text" NOT NULL,
    "modloader" "text" NOT NULL,
    "modloader_version" "text",
    "icon" character varying,
    "cover_image" character varying,
    "title_image" character varying,
    "description" character varying,
    "download_url" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."versions" OWNER TO "postgres";


ALTER TABLE "public"."versions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."versions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."modpacks"
    ADD CONSTRAINT "modpacks_backet_path_key" UNIQUE ("backet_path");



ALTER TABLE ONLY "public"."modpacks"
    ADD CONSTRAINT "modpacks_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."modpacks"
    ADD CONSTRAINT "modpacks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."versions"
    ADD CONSTRAINT "versions_download_url_key" UNIQUE ("download_url");



ALTER TABLE ONLY "public"."versions"
    ADD CONSTRAINT "versions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."versions"
    ADD CONSTRAINT "versions_modpack_name_fkey" FOREIGN KEY ("modpack_name") REFERENCES "public"."modpacks"("name") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."modpacks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."versions" DISABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."versions" ADD COLUMN "title" character varying;


ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";