name: Build and Release Freshcraft

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - freshcraft

jobs:
  build-and-release:
    if: github.ref == 'refs/heads/freshcraft' || (github.ref_type == 'tag' && contains(github.ref_name, '.'))
    uses: ./.github/workflows/build-template.yml
    with:
      build_command_mac: yarn build:mac:freshcraft
      build_command_win: yarn build:win:freshcraft
      custom_env: |
        {
            "VITE_UI_TYPE": "FreshCraft"
        }   
    secrets: inherit 