name: Build and Release Electron App (Main)

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-and-release:
    uses: ./.github/workflows/build-template.yml
    with:
      build_command_mac: yarn build:mac
      build_command_win: yarn build:win
    secrets: inherit 